/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'pynk.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.android-arm64.node')
          } else {
            nativeBinding = require('@pynk/pynk-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'pynk.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.android-arm-eabi.node')
          } else {
            nativeBinding = require('@pynk/pynk-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'pynk.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@pynk/pynk-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'pynk.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@pynk/pynk-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'pynk.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@pynk/pynk-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'pynk.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./pynk.darwin-universal.node')
      } else {
        nativeBinding = require('@pynk/pynk-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'pynk.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.darwin-x64.node')
          } else {
            nativeBinding = require('@pynk/pynk-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'pynk.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.darwin-arm64.node')
          } else {
            nativeBinding = require('@pynk/pynk-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'pynk.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./pynk.freebsd-x64.node')
      } else {
        nativeBinding = require('@pynk/pynk-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-x64-musl.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pynk.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pynk.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@pynk/pynk-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'pynk.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pynk.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@pynk/pynk-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { TorClient, TorClientBuilder, ConfigCircuitTiming, ConfigDirectoryTolerance, ConfigDownloadSchedule, ConfigNetParams, ConfigPathRules, ConfigPreemptiveCircuits, ConfigStorage, ConfigStreamTimeouts, PaddingLevel, TorClientConfig, OnionServiceConfig, OnionV3, RendRequest, OnionService, StateOnionService, StreamRequest, StreamsRequest, TorStream, StreamPrefs } = nativeBinding

module.exports.TorClient = TorClient
module.exports.TorClientBuilder = TorClientBuilder
module.exports.ConfigCircuitTiming = ConfigCircuitTiming
module.exports.ConfigDirectoryTolerance = ConfigDirectoryTolerance
module.exports.ConfigDownloadSchedule = ConfigDownloadSchedule
module.exports.ConfigNetParams = ConfigNetParams
module.exports.ConfigPathRules = ConfigPathRules
module.exports.ConfigPreemptiveCircuits = ConfigPreemptiveCircuits
module.exports.ConfigStorage = ConfigStorage
module.exports.ConfigStreamTimeouts = ConfigStreamTimeouts
module.exports.PaddingLevel = PaddingLevel
module.exports.TorClientConfig = TorClientConfig
module.exports.OnionServiceConfig = OnionServiceConfig
module.exports.OnionV3 = OnionV3
module.exports.RendRequest = RendRequest
module.exports.OnionService = OnionService
module.exports.StateOnionService = StateOnionService
module.exports.StreamRequest = StreamRequest
module.exports.StreamsRequest = StreamsRequest
module.exports.TorStream = TorStream
module.exports.StreamPrefs = StreamPrefs
